/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedUtilitiesRouteImport } from './routes/_authed/utilities'
import { Route as AuthedStaffRouteImport } from './routes/_authed/staff'
import { Route as AuthedRoomsRouteImport } from './routes/_authed/rooms'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedMealsRouteImport } from './routes/_authed/meals'
import { Route as AuthedDepositsRouteImport } from './routes/_authed/deposits'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedBazarRouteImport } from './routes/_authed/bazar'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUtilitiesRoute = AuthedUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStaffRoute = AuthedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRoomsRoute = AuthedRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMealsRoute = AuthedMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDepositsRoute = AuthedDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBazarRoute = AuthedBazarRouteImport.update({
  id: '/bazar',
  path: '/bazar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRoute
  '/bazar': typeof AuthedBazarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/deposits': typeof AuthedDepositsRoute
  '/meals': typeof AuthedMealsRoute
  '/members': typeof AuthedMembersRoute
  '/reports': typeof AuthedReportsRoute
  '/rooms': typeof AuthedRoomsRoute
  '/staff': typeof AuthedStaffRoute
  '/utilities': typeof AuthedUtilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRoute
  '/bazar': typeof AuthedBazarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/deposits': typeof AuthedDepositsRoute
  '/meals': typeof AuthedMealsRoute
  '/members': typeof AuthedMembersRoute
  '/reports': typeof AuthedReportsRoute
  '/rooms': typeof AuthedRoomsRoute
  '/staff': typeof AuthedStaffRoute
  '/utilities': typeof AuthedUtilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/bazar': typeof AuthedBazarRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/deposits': typeof AuthedDepositsRoute
  '/_authed/meals': typeof AuthedMealsRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/rooms': typeof AuthedRoomsRoute
  '/_authed/staff': typeof AuthedStaffRoute
  '/_authed/utilities': typeof AuthedUtilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/bazar'
    | '/dashboard'
    | '/deposits'
    | '/meals'
    | '/members'
    | '/reports'
    | '/rooms'
    | '/staff'
    | '/utilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/bazar'
    | '/dashboard'
    | '/deposits'
    | '/meals'
    | '/members'
    | '/reports'
    | '/rooms'
    | '/staff'
    | '/utilities'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/bazar'
    | '/_authed/dashboard'
    | '/_authed/deposits'
    | '/_authed/meals'
    | '/_authed/members'
    | '/_authed/reports'
    | '/_authed/rooms'
    | '/_authed/staff'
    | '/_authed/utilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/utilities': {
      id: '/_authed/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof AuthedUtilitiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/staff': {
      id: '/_authed/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthedStaffRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rooms': {
      id: '/_authed/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthedRoomsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/meals': {
      id: '/_authed/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof AuthedMealsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deposits': {
      id: '/_authed/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AuthedDepositsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bazar': {
      id: '/_authed/bazar'
      path: '/bazar'
      fullPath: '/bazar'
      preLoaderRoute: typeof AuthedBazarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedBazarRoute: typeof AuthedBazarRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDepositsRoute: typeof AuthedDepositsRoute
  AuthedMealsRoute: typeof AuthedMealsRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedRoomsRoute: typeof AuthedRoomsRoute
  AuthedStaffRoute: typeof AuthedStaffRoute
  AuthedUtilitiesRoute: typeof AuthedUtilitiesRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedBazarRoute: AuthedBazarRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDepositsRoute: AuthedDepositsRoute,
  AuthedMealsRoute: AuthedMealsRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedRoomsRoute: AuthedRoomsRoute,
  AuthedStaffRoute: AuthedStaffRoute,
  AuthedUtilitiesRoute: AuthedUtilitiesRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
